# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vcnnbd_wrapper.xdc

# Block Designs: bd/vcnnbd/vcnnbd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd || ORIG_REF_NAME==vcnnbd}]

# IP: bd/vcnnbd/ip/vcnnbd_processing_system7_0_0/vcnnbd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_processing_system7_0_0 || ORIG_REF_NAME==vcnnbd_processing_system7_0_0}]

# IP: bd/vcnnbd/ip/vcnnbd_blk_mem_gen_0_0/vcnnbd_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_blk_mem_gen_0_0 || ORIG_REF_NAME==vcnnbd_blk_mem_gen_0_0}]

# IP: bd/vcnnbd/ip/vcnnbd_axi_bram_ctrl_0_0/vcnnbd_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==vcnnbd_axi_bram_ctrl_0_0}]

# IP: bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_axi_smc_0 || ORIG_REF_NAME==vcnnbd_axi_smc_0}]

# IP: bd/vcnnbd/ip/vcnnbd_rst_ps7_0_100M_0/vcnnbd_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_rst_ps7_0_100M_0 || ORIG_REF_NAME==vcnnbd_rst_ps7_0_100M_0}]

# IP: bd/vcnnbd/ip/vcnnbd_axi_lite_slave_0_2/vcnnbd_axi_lite_slave_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_axi_lite_slave_0_2 || ORIG_REF_NAME==vcnnbd_axi_lite_slave_0_2}]

# IP: bd/vcnnbd/ip/vcnnbd_conv1l_top_0_0/vcnnbd_conv1l_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_conv1l_top_0_0 || ORIG_REF_NAME==vcnnbd_conv1l_top_0_0}]

# IP: bd/vcnnbd/ip/vcnnbd_blk_mem_gen_0_1/vcnnbd_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_blk_mem_gen_0_1 || ORIG_REF_NAME==vcnnbd_blk_mem_gen_0_1}]

# IP: bd/vcnnbd/ip/vcnnbd_weight_bram_0/vcnnbd_weight_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_weight_bram_0 || ORIG_REF_NAME==vcnnbd_weight_bram_0}]

# IP: bd/vcnnbd/ip/vcnnbd_blk_mem_gen_1_0/vcnnbd_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_blk_mem_gen_1_0 || ORIG_REF_NAME==vcnnbd_blk_mem_gen_1_0}]

# IP: bd/vcnnbd/ip/vcnnbd_output_bram_mem_0/vcnnbd_output_bram_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_output_bram_mem_0 || ORIG_REF_NAME==vcnnbd_output_bram_mem_0}]

# IP: bd/vcnnbd/ip/vcnnbd_conv1l_top_0_1/vcnnbd_conv1l_top_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_conv1l_top_0_1 || ORIG_REF_NAME==vcnnbd_conv1l_top_0_1}]

# IP: bd/vcnnbd/ip/vcnnbd_output_bram_mem_1/vcnnbd_output_bram_mem_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_output_bram_mem_1 || ORIG_REF_NAME==vcnnbd_output_bram_mem_1}]

# IP: bd/vcnnbd/ip/vcnnbd_axi_lite_slave_0_0/vcnnbd_axi_lite_slave_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcnnbd_axi_lite_slave_0_0 || ORIG_REF_NAME==vcnnbd_axi_lite_slave_0_0}]

# XDC: bd/vcnnbd/vcnnbd_ooc.xdc
