# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/axi4lslave/axi4lslave.cache/wt [current_project]
set_property parent.project_path /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/axi4lslave/axi4lslave.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/axi4lslave/axi4lslave.srcs/sources_1/imports [current_project]
set_property ip_output_repo /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/axi4lslave/axi4lslave.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/axi4lslave/axi4lslave.srcs/sources_1/imports/verilog/axi_lite_slave.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top axi_lite_slave -part xc7z020clg400-1


write_checkpoint -force -noxdef axi_lite_slave.dcp

catch { report_utilization -file axi_lite_slave_utilization_synth.rpt -pb axi_lite_slave_utilization_synth.pb }
