set_property SRC_FILE_INFO {cfile:/home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/constrs_1/new/vcnnbd_wrapper.xdc rfile:../../../vcnn.srcs/constrs_1/new/vcnnbd_wrapper.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list vcnnbd_i/conv1l_top_0_input_bram_rd_EN]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list vcnnbd_i/conv1l_top_0_output_bram_wr_EN]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list vcnnbd_i/conv1l_top_0_weight_bram_rd_EN]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[0]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[1]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[2]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[3]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[4]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[5]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[6]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[7]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[8]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[9]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[10]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[11]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[12]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[13]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[14]} {vcnnbd_i/conv1l_top_1/weight_bram_rd_adddr[15]}]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe40 [get_nets [list vcnnbd_i/conv1l_top_0/inst/mult_a_rdy]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe41 [get_nets [list vcnnbd_i/conv1l_top_0/inst/mult_b_rdy]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list vcnnbd_i/conv1l_top_0/inst/mult_c_rdy]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list vcnnbd_i/conv1l_top_1/output_bram_wr_en]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list vcnnbd_i/conv1l_top_1/output_bram_wr_rst]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe79 [get_nets [list vcnnbd_i/conv1l_top_0/inst/n_conv_state1]]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {vcnnbd_i/conv1l_top_0/inst/conv_iaddr1[0]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr1[1]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr1[2]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr1[3]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr1[4]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr1[5]}]]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[0]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[1]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[2]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[3]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[4]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[5]} {vcnnbd_i/conv1l_top_0/inst/conv_iaddr0[6]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe52 [get_nets [list {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[0]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[1]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[2]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[3]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[4]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[5]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[6]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[7]} {vcnnbd_i/conv1l_top_0/inst/conv_waddr1[8]}]]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe55 [get_nets [list {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[0]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[1]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[2]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[3]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[4]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[5]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[6]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[7]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[8]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr1[9]}]]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe58 [get_nets [list {vcnnbd_i/conv1l_top_1/inst/conv_waddr2[0]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr2[1]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr2[2]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr2[3]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr2[4]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr2[5]}]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe61 [get_nets [list {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[0]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[1]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[2]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[3]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[4]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[5]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[6]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[7]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[8]} {vcnnbd_i/conv1l_top_1/inst/conv_waddr0[9]}]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list {vcnnbd_i/weight_bram/bram_addr_a[2]} {vcnnbd_i/weight_bram/bram_addr_a[3]} {vcnnbd_i/weight_bram/bram_addr_a[4]} {vcnnbd_i/weight_bram/bram_addr_a[5]} {vcnnbd_i/weight_bram/bram_addr_a[6]} {vcnnbd_i/weight_bram/bram_addr_a[7]} {vcnnbd_i/weight_bram/bram_addr_a[8]} {vcnnbd_i/weight_bram/bram_addr_a[9]} {vcnnbd_i/weight_bram/bram_addr_a[10]} {vcnnbd_i/weight_bram/bram_addr_a[11]} {vcnnbd_i/weight_bram/bram_addr_a[12]}]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list {vcnnbd_i/weight_bram/bram_we_a[0]} {vcnnbd_i/weight_bram/bram_we_a[1]} {vcnnbd_i/weight_bram/bram_we_a[2]} {vcnnbd_i/weight_bram/bram_we_a[3]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe47 [get_nets [list {vcnnbd_i/weight_bram/bram_wrdata_a[0]} {vcnnbd_i/weight_bram/bram_wrdata_a[1]} {vcnnbd_i/weight_bram/bram_wrdata_a[2]} {vcnnbd_i/weight_bram/bram_wrdata_a[3]} {vcnnbd_i/weight_bram/bram_wrdata_a[4]} {vcnnbd_i/weight_bram/bram_wrdata_a[5]} {vcnnbd_i/weight_bram/bram_wrdata_a[6]} {vcnnbd_i/weight_bram/bram_wrdata_a[7]} {vcnnbd_i/weight_bram/bram_wrdata_a[8]} {vcnnbd_i/weight_bram/bram_wrdata_a[9]} {vcnnbd_i/weight_bram/bram_wrdata_a[10]} {vcnnbd_i/weight_bram/bram_wrdata_a[11]} {vcnnbd_i/weight_bram/bram_wrdata_a[12]} {vcnnbd_i/weight_bram/bram_wrdata_a[13]} {vcnnbd_i/weight_bram/bram_wrdata_a[14]} {vcnnbd_i/weight_bram/bram_wrdata_a[15]} {vcnnbd_i/weight_bram/bram_wrdata_a[16]} {vcnnbd_i/weight_bram/bram_wrdata_a[17]} {vcnnbd_i/weight_bram/bram_wrdata_a[18]} {vcnnbd_i/weight_bram/bram_wrdata_a[19]} {vcnnbd_i/weight_bram/bram_wrdata_a[20]} {vcnnbd_i/weight_bram/bram_wrdata_a[21]} {vcnnbd_i/weight_bram/bram_wrdata_a[22]} {vcnnbd_i/weight_bram/bram_wrdata_a[23]} {vcnnbd_i/weight_bram/bram_wrdata_a[24]} {vcnnbd_i/weight_bram/bram_wrdata_a[25]} {vcnnbd_i/weight_bram/bram_wrdata_a[26]} {vcnnbd_i/weight_bram/bram_wrdata_a[27]} {vcnnbd_i/weight_bram/bram_wrdata_a[28]} {vcnnbd_i/weight_bram/bram_wrdata_a[29]} {vcnnbd_i/weight_bram/bram_wrdata_a[30]} {vcnnbd_i/weight_bram/bram_wrdata_a[31]}]]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe54 [get_nets [list vcnnbd_i/weight_bram/bram_en_a]]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe55 [get_nets [list vcnnbd_i/weight_bram/bram_rst_a]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe78 [get_nets [list vcnnbd_i/weight_bram/s_axi_aresetn]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe79 [get_nets [list vcnnbd_i/weight_bram/s_axi_arready]]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe80 [get_nets [list vcnnbd_i/weight_bram/s_axi_arvalid]]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe81 [get_nets [list vcnnbd_i/weight_bram/s_axi_awready]]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe82 [get_nets [list vcnnbd_i/weight_bram/s_axi_awvalid]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe83 [get_nets [list vcnnbd_i/weight_bram/s_axi_bready]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe84 [get_nets [list vcnnbd_i/weight_bram/s_axi_bvalid]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe85 [get_nets [list vcnnbd_i/weight_bram/s_axi_rlast]]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe86 [get_nets [list vcnnbd_i/weight_bram/s_axi_rready]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe87 [get_nets [list vcnnbd_i/weight_bram/s_axi_rvalid]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe88 [get_nets [list vcnnbd_i/weight_bram/s_axi_wlast]]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe89 [get_nets [list vcnnbd_i/weight_bram/s_axi_wready]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe90 [get_nets [list vcnnbd_i/weight_bram/s_axi_wvalid]]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
