# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci
# IP: The module: 'fp_mult_add_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_mult_add_16bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci
# IP: The module: 'fp_mult_add_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp_mult_add_16bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
