# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.cache/wt [current_project]
set_property parent.project_path /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1 [current_project]
set_property ip_output_repo /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_ooc.xdc]
set_property is_locked true [get_files /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1 -new_name fp_mult_add_16bit -ip [get_ips fp_mult_add_16bit]]

if { $cached_ip eq {} } {

synth_design -top fp_mult_add_16bit -part xc7z020clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix fp_mult_add_16bit_ fp_mult_add_16bit.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fp_mult_add_16bit_stub.v
 lappend ipCachedFiles fp_mult_add_16bit_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fp_mult_add_16bit_stub.vhdl
 lappend ipCachedFiles fp_mult_add_16bit_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fp_mult_add_16bit_sim_netlist.v
 lappend ipCachedFiles fp_mult_add_16bit_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fp_mult_add_16bit_sim_netlist.vhdl
 lappend ipCachedFiles fp_mult_add_16bit_sim_netlist.vhdl

 config_ip_cache -add -dcp fp_mult_add_16bit.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips fp_mult_add_16bit]
}

rename_ref -prefix_all fp_mult_add_16bit_

write_checkpoint -force -noxdef fp_mult_add_16bit.dcp

catch { report_utilization -file fp_mult_add_16bit_utilization_synth.rpt -pb fp_mult_add_16bit_utilization_synth.pb }

if { [catch {
  file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1/fp_mult_add_16bit.dcp /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1/fp_mult_add_16bit.dcp /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1/fp_mult_add_16bit_stub.v /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1/fp_mult_add_16bit_stub.vhdl /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1/fp_mult_add_16bit_sim_netlist.v /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.runs/fp_mult_add_16bit_synth_1/fp_mult_add_16bit_sim_netlist.vhdl /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.ip_user_files/ip/fp_mult_add_16bit]} {
  catch { 
    file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_stub.v /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.ip_user_files/ip/fp_mult_add_16bit
  }
}

if {[file isdir /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.ip_user_files/ip/fp_mult_add_16bit]} {
  catch { 
    file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_stub.vhdl /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.ip_user_files/ip/fp_mult_add_16bit
  }
}
