# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_conv1l_top_0_1/vcnnbd_conv1l_top_0_1.xci
# IP: The module: 'vcnnbd_conv1l_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_conv1l_top_0_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_mult_add_16bit || ORIG_REF_NAME==fp_mult_add_16bit}]

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_conv1l_top_0_1/vcnnbd_conv1l_top_0_1.xci
# IP: The module: 'vcnnbd_conv1l_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_conv1l_top_0_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fp_mult_add_16bit || ORIG_REF_NAME==fp_mult_add_16bit}]
