# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.xci
# IP: The module: 'vcnnbd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/bd_cc5a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_10/bd_cc5a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_16/bd_cc5a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_23/bd_cc5a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_30/bd_cc5a_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_37/bd_cc5a_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_43/bd_cc5a_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_38/bd_cc5a_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_39/bd_cc5a_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_40/bd_cc5a_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_41/bd_cc5a_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_42/bd_cc5a_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_36/bd_cc5a_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_31/bd_cc5a_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_32/bd_cc5a_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_33/bd_cc5a_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_34/bd_cc5a_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_35/bd_cc5a_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_29/bd_cc5a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_24/bd_cc5a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_25/bd_cc5a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_26/bd_cc5a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_27/bd_cc5a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_28/bd_cc5a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_22/bd_cc5a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_17/bd_cc5a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_18/bd_cc5a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_19/bd_cc5a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_20/bd_cc5a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_21/bd_cc5a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_11/bd_cc5a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_12/bd_cc5a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_13/bd_cc5a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_14/bd_cc5a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_15/bd_cc5a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_7/bd_cc5a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_8/bd_cc5a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_9/bd_cc5a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_2/bd_cc5a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_3/bd_cc5a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_4/bd_cc5a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_5/bd_cc5a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_6/bd_cc5a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_0/bd_cc5a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcnnbd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_10/bd_cc5a_s00a2s_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_16/bd_cc5a_m00s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_23/bd_cc5a_m01s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_30/bd_cc5a_m02s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_37/bd_cc5a_m03s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_38/bd_cc5a_m03arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_39/bd_cc5a_m03rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_40/bd_cc5a_m03awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_41/bd_cc5a_m03wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_42/bd_cc5a_m03bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_31/bd_cc5a_m02arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_32/bd_cc5a_m02rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_33/bd_cc5a_m02awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_34/bd_cc5a_m02wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_35/bd_cc5a_m02bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_24/bd_cc5a_m01arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_25/bd_cc5a_m01rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_26/bd_cc5a_m01awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_27/bd_cc5a_m01wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_28/bd_cc5a_m01bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_17/bd_cc5a_m00arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_18/bd_cc5a_m00rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_19/bd_cc5a_m00awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_20/bd_cc5a_m00wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_21/bd_cc5a_m00bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_11/bd_cc5a_sarn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_12/bd_cc5a_srn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_13/bd_cc5a_sawn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_14/bd_cc5a_swn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_15/bd_cc5a_sbn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_2/bd_cc5a_arsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_3/bd_cc5a_rsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_4/bd_cc5a_awsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_5/bd_cc5a_wsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_6/bd_cc5a_bsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.xci
# IP: The module: 'vcnnbd_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/bd_cc5a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_10/bd_cc5a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_16/bd_cc5a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_23/bd_cc5a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_30/bd_cc5a_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_37/bd_cc5a_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_43/bd_cc5a_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_38/bd_cc5a_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_39/bd_cc5a_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_40/bd_cc5a_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_41/bd_cc5a_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_42/bd_cc5a_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_36/bd_cc5a_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_31/bd_cc5a_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_32/bd_cc5a_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_33/bd_cc5a_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_34/bd_cc5a_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_35/bd_cc5a_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_29/bd_cc5a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_24/bd_cc5a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_25/bd_cc5a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_26/bd_cc5a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_27/bd_cc5a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_28/bd_cc5a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_22/bd_cc5a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_17/bd_cc5a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_18/bd_cc5a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_19/bd_cc5a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_20/bd_cc5a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_21/bd_cc5a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_11/bd_cc5a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_12/bd_cc5a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_13/bd_cc5a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_14/bd_cc5a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_15/bd_cc5a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_7/bd_cc5a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_8/bd_cc5a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_9/bd_cc5a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_2/bd_cc5a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_3/bd_cc5a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_4/bd_cc5a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_5/bd_cc5a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_6/bd_cc5a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_0/bd_cc5a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vcnnbd_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_10/bd_cc5a_s00a2s_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_16/bd_cc5a_m00s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_23/bd_cc5a_m01s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_30/bd_cc5a_m02s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_37/bd_cc5a_m03s2a_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_38/bd_cc5a_m03arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_39/bd_cc5a_m03rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_40/bd_cc5a_m03awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_41/bd_cc5a_m03wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_42/bd_cc5a_m03bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_31/bd_cc5a_m02arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_32/bd_cc5a_m02rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_33/bd_cc5a_m02awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_34/bd_cc5a_m02wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_35/bd_cc5a_m02bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_24/bd_cc5a_m01arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_25/bd_cc5a_m01rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_26/bd_cc5a_m01awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_27/bd_cc5a_m01wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_28/bd_cc5a_m01bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_17/bd_cc5a_m00arn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_18/bd_cc5a_m00rn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_19/bd_cc5a_m00awn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_20/bd_cc5a_m00wn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_21/bd_cc5a_m00bn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_11/bd_cc5a_sarn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_12/bd_cc5a_srn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_13/bd_cc5a_sawn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_14/bd_cc5a_swn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_15/bd_cc5a_sbn_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_2/bd_cc5a_arsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_3/bd_cc5a_rsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_4/bd_cc5a_awsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_5/bd_cc5a_wsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_6/bd_cc5a_bsw_0_ooc.xdc

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.
