# 
# Synthesis run script generated by Vivado
# 

set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.cache/wt [current_project]
set_property parent.project_path /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/gokul/playground/ece594bb/fpgacc/vcnn/ip [current_project]
set_property ip_output_repo /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.xci
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_10/bd_cc5a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_16/bd_cc5a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_23/bd_cc5a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_30/bd_cc5a_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_37/bd_cc5a_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_38/bd_cc5a_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_39/bd_cc5a_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_40/bd_cc5a_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_41/bd_cc5a_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_42/bd_cc5a_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_31/bd_cc5a_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_32/bd_cc5a_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_33/bd_cc5a_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_34/bd_cc5a_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_35/bd_cc5a_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_24/bd_cc5a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_25/bd_cc5a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_26/bd_cc5a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_27/bd_cc5a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_28/bd_cc5a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_17/bd_cc5a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_18/bd_cc5a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_19/bd_cc5a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_20/bd_cc5a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_21/bd_cc5a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_11/bd_cc5a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_12/bd_cc5a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_13/bd_cc5a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_14/bd_cc5a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_15/bd_cc5a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_2/bd_cc5a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_3/bd_cc5a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_4/bd_cc5a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_5/bd_cc5a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_6/bd_cc5a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/bd_2/ip/ip_1/bd_cc5a_psr_aclk_0.xdc]
set_property is_locked true [get_files /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1 -new_name vcnnbd_axi_smc_0 -ip [get_ips vcnnbd_axi_smc_0]]

if { $cached_ip eq {} } {

synth_design -top vcnnbd_axi_smc_0 -part xc7z020clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix vcnnbd_axi_smc_0_ vcnnbd_axi_smc_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vcnnbd_axi_smc_0_stub.v
 lappend ipCachedFiles vcnnbd_axi_smc_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vcnnbd_axi_smc_0_stub.vhdl
 lappend ipCachedFiles vcnnbd_axi_smc_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vcnnbd_axi_smc_0_sim_netlist.v
 lappend ipCachedFiles vcnnbd_axi_smc_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ vcnnbd_axi_smc_0_sim_netlist.vhdl
 lappend ipCachedFiles vcnnbd_axi_smc_0_sim_netlist.vhdl

 config_ip_cache -add -dcp vcnnbd_axi_smc_0.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips vcnnbd_axi_smc_0]
}

rename_ref -prefix_all vcnnbd_axi_smc_0_

write_checkpoint -force -noxdef vcnnbd_axi_smc_0.dcp

catch { report_utilization -file vcnnbd_axi_smc_0_utilization_synth.rpt -pb vcnnbd_axi_smc_0_utilization_synth.pb }

if { [catch {
  file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1/vcnnbd_axi_smc_0.dcp /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1/vcnnbd_axi_smc_0.dcp /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1/vcnnbd_axi_smc_0_stub.v /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1/vcnnbd_axi_smc_0_stub.vhdl /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1/vcnnbd_axi_smc_0_sim_netlist.v /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.runs/vcnnbd_axi_smc_0_synth_1/vcnnbd_axi_smc_0_sim_netlist.vhdl /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.ip_user_files/ip/vcnnbd_axi_smc_0]} {
  catch { 
    file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_stub.v /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.ip_user_files/ip/vcnnbd_axi_smc_0
  }
}

if {[file isdir /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.ip_user_files/ip/vcnnbd_axi_smc_0]} {
  catch { 
    file copy -force /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.srcs/sources_1/bd/vcnnbd/ip/vcnnbd_axi_smc_0/vcnnbd_axi_smc_0_stub.vhdl /home/gokul/playground/ece594bb/fpgacc/vcnn/vcnn.ip_user_files/ip/vcnnbd_axi_smc_0
  }
}
