# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.cache/wt [current_project]
set_property parent.project_path /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1 [current_project]
set_property ip_output_repo /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/new/conv1l_top.v
read_ip -quiet /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci
set_property used_in_implementation false [get_files -all /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit_ooc.xdc]
set_property is_locked true [get_files /home/gokul/playground/ece594bb/fpgacc/vcnn/ip/convl1/convl1.srcs/sources_1/ip/fp_mult_add_16bit/fp_mult_add_16bit.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top conv1l_top -part xc7z020clg400-1


write_checkpoint -force -noxdef conv1l_top.dcp

catch { report_utilization -file conv1l_top_utilization_synth.rpt -pb conv1l_top_utilization_synth.pb }
